[build]
  base = "c1/my-website/my-app"
  command = "npm install && npm run build"
  publish = "dist"
  functions = "c1/my-website/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
